spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

oauth:
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: ${KAKAO_REDIRECT_URI}
    client_secret: ${KAKAO_CLIENT_SECRET}
    scope: ${KAKAO_SCOPE}

  naver:
    client_id: ${NAVER_CLIENT_ID}
    redirect_uri: ${NAVER_REDIRECT_URI}
    client_secret: ${NAVER_CLIENT_SECRET}
    scope: ${NAVER_SCOPE}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
